config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customer, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: 'public/homes#top'

  namespace :admin do
    resources :order_details, only: [:show]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :index, :show, :edit, :create, :update]
    root to: 'homes#top'
  end
  namespace :public do
    post 'orders/confirm', as: 'order_confirm'
    get 'orders/finish', as: 'order_finish'
    get 'customers/:id/confirm_withdraw' => 'customers#confirm_withdraw', as: 'customer_confirm_withdraw'
    resources :orders, only: [:new, :create, :index, :show]
    resources :cart_items, only: [:index, :create]
    resources :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
    patch 'customers/:id/withdraw' => 'customers#withdraw', as: 'customer_withdraw'
    patch 'cart_items/update/:id' => 'cart_items#update', as: 'cart_item_update'
    delete 'cart_items/destroy/:id' => 'cart_items#destroy', as: 'cart_item_destroy'
    delete 'cart_items/destroy_all', as: 'cart_items_destroy_all'
    get "/homes/about" => "homes#about", as: 'about'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def with_tax_price
    (price * 1.1).floor
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [250, 300]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    @total = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path
    else
      render :index
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/items/edit.html.erb
<div class = "container">
  <h2>商品編集</h2>
  <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <%= form_with model: [:admin,@item] do |f| %>
      <p>商品画像<%= f.file_field :image, accept: "image" %></p>
      <p>商品名<%= f.text_field :name, autofocus: true %></p>
      <p>商品説明<%= f.text_area :introduction, autofocus: true %></p>
      <p>税抜価格<%= f.text_field :price, autofocus: true %></p>
      <%= f.submit "変更を保存", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class = 'container'>
  <h2>
    商品一覧
    <%= link_to new_admin_item_path do %>
      <i class="fa-solid fa-circle-plus"></i>
    <% end %>
  </h2>

  <table class = 'table table-bordered'>
    <therd>
      <tr>
        <th>
          <p>商品ID</p>
        </th>
        <th>
          <p>商品名</p>
        </th>
        <th>
          <p>税抜価格</p>
        </th>
      </tr>
    </therd>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td>
            <%= item.id %>
          </td>
          <td>
            <%= link_to admin_item_path(item.id) do %>
              <%= item.name %>
            <% end %>
          </td>
          <td>
            <%= item.price %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/items/new.html.erb
<div class = "container">
  <h2>商品新規登録</h2>
  <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <%= form_with model: [:admin,@item] do |f| %>
      <div class = "form-group">
        <p>商品画像<%= f.file_field :image, accept: "image/*" %></p>
      </div>
      <div class = "form-group">
        <p>商品名<%= f.text_field :name %></p>
      </div>
      <div class = "form-group">
        <p>商品説明<%= f.text_area :introduction %></p>
      </div>
      <div class = "form-group">
        <p>税抜価格<%= f.text_field :price %>円</p>
      </div>
      <div class = "form-group">
        <%= f.submit "新規登録", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class = "container">
  <h4>商品詳細</h4>
  <%= image_tag @item.get_image %>
  <p>商品名&emsp;<%= @item.name %></p>
  <p>商品説明&emsp;<%= @item.introduction %></p>
  <p>税込価格(税抜価格)&emsp;<%= @item.with_tax_price %> (<%= @item.price %>)円</p>
  <%= link_to "編集する", edit_admin_item_path, class: "btn btn-success" %>
</div>