config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customer, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: 'public/homes#top'

  namespace :admin do
    resources :order_details, only: [:show]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :index, :show, :edit, :create, :update]
    root to: 'homes#top'
  end
  namespace :public do
    post 'orders/confirm', as: 'order_confirm'
    get 'orders/finish', as: 'order_finish'
    get 'customers/:id/confirm_withdraw' => 'customers#confirm_withdraw', as: 'customer_confirm_withdraw'
    resources :orders, only: [:new, :create, :index, :show]
    resources :cart_items, only: [:index, :create]
    resources :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
    patch 'customers/:id/withdraw' => 'customers#withdraw', as: 'customer_withdraw'
    patch 'cart_items/update/:id' => 'cart_items#update', as: 'cart_item_update'
    delete 'cart_items/destroy/:id' => 'cart_items#destroy', as: 'cart_item_destroy'
    delete 'cart_items/destroy_all', as: 'cart_items_destroy_all'
    get "/homes/about" => "homes#about", as: 'about'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def with_tax_price
    (price * 1.1).floor
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [250, 300]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customers_path
    else
      render :index
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    @total = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path
    else
      render :index
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/customers/edit.html.erb
<div class = "container">
  <h4>会員情報編集</h4>
  <p class = "form-group">
    <div class = "col-xs-2">
      会員ID
    </div>
    <div class = "col-xs-10">
      <%= @customer.id %>
    </div>
  </p>
  <%= form_with model: @customer, url: admin_customer_path do |f| %>
    <p class = "form-group">
      <div class = "col-xs-2">
        氏名
      </div>
      <div class = "col-xs-10">
        <%= f.text_field :last_name, autofocus: true %><%= f.text_field :first_name, autofocus: true %>
      </div>
    </p>
    <p class = "form-group">
      <div class = "col-xs-2">
        フリガナ
      </div>
      <div class = "col-xs-10">
        <%= f.text_field :last_name_kana, autofocus: true %>
      </div>
    </p>
    <p class = "form-group">
      <div class = "col-xs-2">
        郵便番号
      </div>
      <div class = "col-xs-10">
        <%= f.text_field :postal_code, autofocus: true %>
      </div>
    </p>
    <p class = "form-group">
      <div class = "col-xs-2">
        住所
      </div>
      <div class = "col-xs-10">
        <%= f.text_area :address, autofocus: true %>
      </div>
    </p>
    <p class = "form-group">
      <div class = "col-xs-2">
        電話番号
      </div>
      <div class = "col-xs-10">
        <%= f.text_field :telephone_number, autofocus: true %>
      </div>
    </p>
    <p class = "form-group">
      <div class = "col-xs-2">
        メールアドレス
      </div>
      <div class = "col-xs-10">
        <%= f.text_field :email, autofocus: true %>
      </div>
    </p>
    <p class = "form-group">
      <div class = "col-xs-2">
        会員ステータス
      </div>
      <div class = "col-xs-10">
        <%= f.radio_button :is_deleted, "0" %>
        <%= f.label :is_deleted, "有効", value: 0 %>

        <%= f.radio_button :is_deleted, "1" %>
        <%= f.label :is_deleted, "退会", value: 1 %>
      </div>
    </p>
    <%= f.submit "変更を保存", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class = "container">
  <h2>会員一覧</h2>
  <table class = "table table-striped">
    <therd>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </therd>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id) do %>
              <%= customer.last_name += customer.first_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_deleted == false %>
              <span>有効</span>
            <% else %>
              <span>退会</span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/customers/show.html.erb
<div class = "container">
  <h2>会員詳細</h2>
  <table class = "table">
    <tr>
      <td>会員ID</td>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= @customer.last_name %><%= @customer.first_name %></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td><%= @customer.postal_code %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <td>会員ステータス</td>
      <td>
        <% if @customer.is_deleted == false %>
          <span>有効</span>
        <% else %>
          <span>退会</span>
        <% end %>
      </td>
    </tr>
  </table>
  <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success" %>
  <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary" %>
</div>