config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customer, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: 'public/homes#top'

  namespace :admin do
    resources :order_details, only: [:show]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :index, :show, :edit, :create, :update]
    root to: 'homes#top'
  end
  namespace :public do
    post 'orders/confirm', as: 'order_confirm'
    get 'orders/finish', as: 'order_finish'
    get 'customers/:id/confirm_withdraw' => 'customers#confirm_withdraw', as: 'customer_confirm_withdraw'
    resources :orders, only: [:new, :create, :index, :show]
    resources :cart_items, only: [:index, :create]
    resources :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
    patch 'customers/:id/withdraw' => 'customers#withdraw', as: 'customer_withdraw'
    patch 'cart_items/update/:id' => 'cart_items#update', as: 'cart_item_update'
    delete 'cart_items/destroy/:id' => 'cart_items#destroy', as: 'cart_item_destroy'
    delete 'cart_items/destroy_all', as: 'cart_items_destroy_all'
    get "/homes/about" => "homes#about", as: 'about'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def with_tax_price
    (price * 1.1).floor
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [250, 300]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c77cf161f0.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header class = "d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
          <h4><%= link_to "nagano cake", root_path, class: "d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none" %></h4>
            <ul class="nav nav-pills">
              <% if customer_signed_in? %>
                <li>
                  <%= link_to "マイページ", public_customer_path(current_customer), class: "btn btn-outline-dark" %>
                </li>
                <li>
                  <%= link_to "商品一覧", public_items_path, class: "btn btn-outline-dark" %>
                </li>
                <li>
                  <%= link_to "カート", public_cart_items_path, class: "btn btn-outline-dark" %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-dark" %>
                </li>
              <% elsif admin_signed_in? %>
                <li>
                  <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-dark" %>
                </li>
                <li>
                  <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-dark" %>
                </li>
                <li>
                  <%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-dark" %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark" %>
                </li>
              <% else %>
                <li>
                  <%= link_to "About", public_about_path, class: "btn btn-outline-dark" %>
                </li>
                <li>
                  <%= link_to "商品一覧", public_items_path, class: "btn btn-outline-dark" %>
                </li>
                <li>
                  <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-dark" %>
                </li>
                <li>
                  <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-dark" %>
                </li>
              <% end %>
            </ul>
      </header>
    </div>
    <%= yield %>
  </body>
</html>